Initial Commit: Notebook Containers
awslabs/kubeflow-manifests pull request #155
Opened 2022-03-29 21:08 UTC by mbaijal

**Which issue is resolved by this Pull Request:**
Make the source code for the Jupyter Images to be used in Kubeflow Notebooks public. 

**Description of your changes:**
Adds - 
 - [ ] Dockerfile and requirements.txt for Tensorflow CPU and GPU
 - [ ] Dockerfile and requirements.txt for Pytorch CPU and GPU
 - [ ] A Readme file. 
 
**TODO:**
 - [ ] requirements.txt is similar - can create a common source
 - [ ] automate build (separate PR)
 - [ ] add a test (separate PR)

**Testing:**
- [ ] Unit tests pass
- [ ] e2e tests pass
- Details about new tests (If this PR adds a new feature)
- Details about any manual tests performed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-03-30 17:11 UTC, mbaijal commented on components/notebook-dockerfiles/pytorch/cpu/Dockerfile
> +# install -- node.js
@mbaijal Check if this is still needed

2022-03-30 17:11 UTC, mbaijal commented on components/notebook-dockerfiles/pytorch/cpu/Dockerfile
> +# Install Docker Client
@mbaijal This can be removed.

2022-03-31 00:15 UTC, goswamig commented on components/notebook-dockerfiles/README.md
> +# Using Kubeflow Notebooks on AWS
This title doesnt comprehend well. 

I believe you're stating using `aws optimized container images for kubeflow notebook` or along this line.

2022-03-31 00:17 UTC, goswamig commented on components/notebook-dockerfiles/pytorch/cpu/Dockerfile
> +# Install Docker Client
why its still here then ?

2022-03-31 00:18 UTC, goswamig commented on components/notebook-dockerfiles/pytorch/cpu/Dockerfile
> +# Install Docker Client
can u please fix it?

2022-03-31 00:24 UTC, goswamig commented on components/notebook-dockerfiles/pytorch/cpu/requirements.txt
> +ml-metadata==1.7.0
why are adding this package here?

2022-03-31 00:25 UTC, goswamig commented on components/notebook-dockerfiles/pytorch/cpu/requirements.txt
> +#torchelastic==0.2.2 this currently causes a dependency conflict, should be fixed very soon
Torchelastic is not a separate package any more, you can remove this line.

2022-03-31 00:30 UTC, goswamig requested changes
If requirements files are same can we write it once? Hard to maintain four copies of it.

2022-04-01 01:07 UTC, mbaijal commented
> If requirements files are same can we write it once? Hard to maintain four copies of it.

I combined the cpu and gpu ones for pytorch and tensorflow but it is best to keep two separate copies since 
1. they have a couple of different packages and this might further change in the future. 
2. Also, in order to combine them into one, I will have to put all four Dockerfiles in the same directory (COPY src needs to be in the docker build context), which is not clean.

2022-04-01 22:00 UTC, goswamig approved these changes

2022-04-06 06:25 UTC, mbaijal commented on components/notebook-dockerfiles/pytorch/cpu.Dockerfile
> +RUN cd /tmp && \
@mbaijal  Check if tini is preinstalled and this step can be skipped

2022-04-06 22:31 UTC, akartsky approved these changes

2022-04-06 22:31 UTC, akartsky commented on components/notebook-dockerfiles/tensorflow/cpu.Dockerfile
> +  python3-setuptools \
[nit] Can we put all of these in alphabetically sorted order 

(same comment for other dockerfiles too)

2022-04-06 22:31 UTC, akartsky commented on components/notebook-dockerfiles/tensorflow/cpu.Dockerfile
> +    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
[nit] Can we put the && in the next line 

(same comment for other dockerfiles too)

2022-04-06 22:31 UTC, akartsky commented on components/notebook-dockerfiles/tensorflow/cpu.Dockerfile
> +    wget --quiet https://github.com/krallin/tini/releases/download/v0.18.0/tini && \
[nit] Can we put the && in the next line

(same comment for other dockerfiles too)

2022-04-12 18:16 UTC, merged