Webside doc fixes
awslabs/kubeflow-manifests pull request #275
Opened 2022-06-23 17:52 UTC by akartsky

Website doc changes 

Deployed here for testing : https://akartsky.github.io/kubeflow-manifests/main

2022-06-23 18:06 UTC, rrrkharse commented
Broken link: https://github.com/awslabs/kubeflow-manifests/blob/main/deployment/vanilla/kustomization.yaml#L57
Fix: https://github.com/awslabs/kubeflow-manifests/blob/main/deployments/vanilla/kustomization.yaml#L57

In [Usage Tracking](https://akartsky.github.io/kubeflow-manifests/docs/about/usage-tracking/)

2022-06-23 18:13 UTC, rrrkharse commented
Broken link: https://akartsky.github.io/kubeflow-manifests/docs/deployment/cognito/guide/kubeflow-manifests/docs/deployment/add-ons/load-balancer/guide#create-certificates-for-domain
Fix: Unsure

Text: If your cluster is not in N.Virginia(us-east-1), create an ACM certificate in us-east-1 for *.platform.example.com by following the process similar to [section 2.0](https://akartsky.github.io/kubeflow-manifests/docs/deployment/cognito/guide/kubeflow-manifests/docs/deployment/add-ons/load-balancer/guide/#create-certificates-for-domain)

2022-06-23 18:14 UTC, rrrkharse commented
Broken link: https://github.com/awslabs/kubeflow-manifests/blob/main/docs/deployment/cognito/README-automated.md
Fix: https://github.com/awslabs/kubeflow-manifests/blob/main/docs/deployments/cognito/README-automated.md

Text: Take note of the following values from the previous step or awsconfigs/infra_configs/scripts/config.yaml if you used the [automated guide](https://github.com/awslabs/kubeflow-manifests/blob/main/docs/deployment/cognito/README-automated.md)

2022-06-23 19:17 UTC, rrrkharse commented
In https://akartsky.github.io/kubeflow-manifests/main/docs/component-guides/kserve/#create-a-certificate

Broken link in:

Create an ACM certificate for *.platform.example.com and *.staging.platform.example.com in your cluster’s region by following the [create certificates for domain](https://akartsky.github.io/kubeflow-manifests/deployments/add-ons/load-balancer/guide/#create-certificates-for-domain) steps in the Load Balancer installation guide.

2022-06-23 19:21 UTC, rrrkharse commented
In https://akartsky.github.io/kubeflow-manifests/main/docs/component-guides/profiles/#component-level-implementations

Broken link in:

You can find documentation about the AwsIamForServiceAccount plugin for specific components in the individual [component guides](https://akartsky.github.io/docs/component-guides/). Read on for general configuration instructions.

Fix: https://akartsky.github.io/kubeflow-manifests/main/docs/component-guides/

2022-06-23 19:23 UTC, rrrkharse requested changes

2022-06-23 19:23 UTC, rrrkharse commented on website/content/en/docs/deployment/cognito/guide-automated.md
> +        2. If `ADDRESS` is empty after a few minutes, check the logs of alb-ingress-controller by following [this guide]({{< ref "/docs/troubleshooting-aws.md#alb-fails-to-provision" >}})
Need this same change [for LB guide](https://akartsky.github.io/kubeflow-manifests/main/docs/deployment/add-ons/load-balancer/guide/#update-the-domain-with-alb-address)

Text:
If ADDRESS is empty after a few minutes, check the logs of the controller by following the troubleshooting steps in [ALB fails to provision](https://awslabs.github.io/kubeflow-manifests/docs/troubleshooting-aws/#alb-fails-to-provision).

2022-06-23 20:51 UTC, surajkota commented
@akartsky I recently merged #272 in which i followed this format for relative link. See this commit - https://github.com/awslabs/kubeflow-manifests/pull/272/commits/6387387b33e71bfb211e66a191c1253dedf3e3bc

Can you please rebase and check if it is correct?

2022-06-27 17:26 UTC, rrrkharse approved these changes

2022-06-27 19:08 UTC, surajkota requested changes
One broken link. Others we can find as we test after this is merged

2022-06-27 19:10 UTC, akartsky commented on website/content/en/docs/component-guides/kserve.md
>  1. Configure the following parameters for [ingress](https://github.com/awslabs/kubeflow-manifests/blob/main/awsconfigs/common/istio-ingress/overlays/api/params.env):
yes 
let me fix this

2022-06-27 19:14 UTC, akartsky commented on website/content/en/docs/component-guides/kserve.md
> -If you are using Cognito for user authentication, see [Cognito](/kubeflow-manifests/docs/component-guides/kserve/#cognito-ingress). If you use Dex as the auth provider in your Kubeflow deployment, se
This was fixed today morning 

https://akartsky.github.io/kubeflow-manifests/main/docs/component-guides/kserve/

2022-06-27 19:17 UTC, akartsky commented on website/content/en/docs/component-guides/kserve.md
>  1. Configure the following parameters for [ingress](https://github.com/awslabs/kubeflow-manifests/blob/main/awsconfigs/common/istio-ingress/overlays/api/params.env):
oh wait this is not even deployed to websites anymore 
so can't do it

2022-06-27 19:21 UTC, surajkota approved these changes

2022-06-27 19:25 UTC, merged