Prometheus, AMP, and AMG Website Guide
awslabs/kubeflow-manifests pull request #296
Opened 2022-07-18 16:48 UTC by BriannaRoskind

**Which issue is resolved by this Pull Request:**
Adds a guide explaining how to setup Prometheus and Amazon Managed Service for Prometheus.
There are also links to the Amazon Managed Grafana documentation explaining how to perform that portion of the setup.

**Description of your changes:**
Added a guide in the website/content/en/docs/deployment/add-ons/prometheus folder.

2022-07-18 16:57 UTC, rrrkharse approved these changes

2022-07-19 20:54 UTC, rrrkharse requested changes

2022-07-19 20:54 UTC, rrrkharse commented on deployments/add-ons/prometheus/README.md
> +    1. `eksctl create iamserviceaccount --name amp-iamproxy-ingest-service-account --namespace monitoring --cluster $CLUSTER_NAME --attach-policy-arn $POLICY_ARN --override-existing-serviceaccounts -
$POLICY_ARN --> $AMP_POLICY_ARN

2022-07-19 20:54 UTC, rrrkharse commented on deployments/add-ons/prometheus/README.md
> +    1. `export CLUSTER_NAME=<your-cluster-name>`
Can we convert the inline code to code blocks:

E.g.
```
export CLUSTER_NAME=<your-cluster-name>
```

I think the inline blocks mess up the `--` dashes which makes the commands fail when you copy paste.

2022-07-19 20:54 UTC, rrrkharse commented on deployments/add-ons/prometheus/README.md
> +    1. `python3 -c 'import os; import e2e.utils.prometheus.setup_prometheus_server as setup_prometheus_server; cluster_region = os.environ["CLUSTER_REGION"]; workspace_id = os.environ["AMP_WORKSPACE_
```
    access_key = os.environ['AWS_ACCESS_KEY_ID']
    secret_key = os.environ['AWS_SECRET_ACCESS_KEY']
```

These need to be exported for the script to work. When testing locally I had to export those variables.

2022-07-19 20:54 UTC, rrrkharse commented on deployments/add-ons/prometheus/README.md
> +    1. `python3 -c 'import os; import e2e.utils.prometheus.setup_prometheus_server as setup_prometheus_server; cluster_region = os.environ["CLUSTER_REGION"]; workspace_id = os.environ["AMP_WORKSPACE_
This step also requires `awscurl` to be installed. We need to add a link in the prerequisites to download `awscurl`.

2022-07-19 20:59 UTC, rrrkharse commented
Could you also move the readme to this folder:
https://github.com/awslabs/kubeflow-manifests/tree/main/website/content/en/docs/deployment/add-ons

2022-07-19 21:21 UTC, rrrkharse approved these changes

2022-07-23 21:36 UTC, ryansteakley approved these changes

2022-07-27 18:06 UTC, merged