update istio and remove kfserving
awslabs/kubeflow-manifests pull request #319
Opened 2022-08-09 21:38 UTC by ryansteakley

**Description of your changes:**

- Upstream is using istio 1-14 and kfserving has been removed

**Testing:**
- [ ] Unit tests pass
- [ ] e2e tests pass
- Details about new tests (If this PR adds a new feature)
- Details about any manual tests performed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-10 05:15 UTC, mbaijal reviewed
Changes look ok but could you please add some details on tests run.

2022-08-10 19:31 UTC, ryansteakley commented
> Changes look ok but could you please add some details on tests run.

Didn't save the test logs, but have verified that they are passing. This pr in particular is mostly concerned with getting our kustomization files to point to the correct paths upstream.

2022-08-16 19:16 UTC, surajkota requested changes
Also change the version in main readme badge, test constant, prerequisites to point to the right upstream versions

2022-08-23 04:49 UTC, mbaijal approved these changes

2022-08-24 05:03 UTC, ryansteakley commented
> Also change the version in main readme badge, test constant, prerequisites to point to the right upstream versions

updatd the test constants. Not sure what you mean by main readme badge. Waiting on pointing pre-reqs to upstream since they are still tagged as rc version and we don't have an aws release either.

2022-08-24 19:10 UTC, surajkota commented on tests/e2e/pa.py
> +import boto3
is it here by mistake?

2022-08-24 19:12 UTC, surajkota requested changes

2022-08-24 19:12 UTC, surajkota commented on website/content/en/docs/component-guides/kserve.md
>  > Note: Kubeflow on AWS v1.4 uses [KFServing](https://www.kubeflow.org/docs/external-add-ons/kserve/kserve/#kfserving-is-now-kservehttpskservegithubiowebsite07blogarticles2021-09-27-kfserving-transit
lets remove both the lines or maybe just add one line about KFServing project is now called KServe wiht this link https://kserve.github.io/website/0.7/blog/articles/2021-09-27-kfserving-transition/#kfserving-is-now-kserve and link to this guide for migration https://kserve.github.io/website/0.7/admin/migration/

2022-08-24 19:17 UTC, ryansteakley commented on tests/e2e/pa.py
> +import boto3
yes will remove it

2022-08-24 19:35 UTC, surajkota approved these changes

2022-08-24 19:35 UTC, surajkota commented on website/content/en/docs/component-guides/kserve.md
> +The KFServing project is now called [KServe](https://kserve.github.io/website/0.7/blog/articles/2021-09-27-kfserving-transition/#kfserving-is-now-kserve). To migrate from KFServing to Kserve follow t
nit: add  `> Note:` before the line

2022-08-24 19:37 UTC, ryansteakley commented on website/content/en/docs/component-guides/kserve.md
> +The KFServing project is now called [KServe](https://kserve.github.io/website/0.7/blog/articles/2021-09-27-kfserving-transition/#kfserving-is-now-kserve). To migrate from KFServing to Kserve follow t
done

2022-08-24 19:38 UTC, merged