Blog/workshop update
awslabs/kubeflow-manifests pull request #533
Opened 2022-12-22 00:41 UTC by npepin-hub

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-12-22 18:35 UTC, ryansteakley approved these changes

2022-12-22 22:33 UTC, surajkota requested changes

2022-12-22 22:33 UTC, surajkota commented on website/content/en/blog/_index.md
> +* Support for distributed training on Amazon SageMaker
Support for running machine learning workloads on Amazon SageMaker from Kubeflow

2022-12-27 19:08 UTC, surajkota approved these changes

2022-12-27 19:09 UTC, surajkota commented
Rebase please

2022-12-27 19:45 UTC, merged