add sample profile to helm/kustomize Cognito-rds-s3
awslabs/kubeflow-manifests pull request #694
Opened 2023-04-20 19:13 UTC by ryansteakley

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Keep parity with Terraform deployment. Adds a sample user-profile configured with s3-bucket access to helm/kustomize cognito-rds-s3 deployments

**Testing:**
- [ ] Unit tests pass
- [ ] e2e tests pass
- Details about new tests (If this PR adds a new feature)
- Details about any manual tests performed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-20 19:30 UTC, surajkota commented on tests/e2e/resources/installation_config/cognito-rds-s3.yaml
> +user-namespace:
please add to cognito as well

2023-04-20 19:54 UTC, ryansteakley commented on tests/e2e/resources/installation_config/cognito-rds-s3.yaml
> +user-namespace:
added to all cognito

2023-04-20 20:39 UTC, surajkota requested changes

2023-04-20 20:39 UTC, surajkota commented on tests/e2e/resources/installation_config/cognito-rds-s3-static.yaml
> +        - ../../awsconfigs/common/user-namespace/overlay
static one should point to upstream not the aws overlay. same for cognito

Can you also update the Cognito guide to create a user with email user@example.com? https://awslabs.github.io/kubeflow-manifests/docs/deployment/cognito/manifest/guide/#60-connect-to-the-central-dashboard

2023-04-20 21:35 UTC, surajkota commented on tests/e2e/resources/installation_config/cognito-rds-s3-static.yaml
> +      paths: ../../charts/common/user-namespace
add if else for the plugin portion of the profile

2023-04-21 16:27 UTC, surajkota approved these changes

2023-04-21 16:39 UTC, ryansteakley commented
Drafting doc changes in separate pr

2023-04-21 16:39 UTC, merged