Update main.tf
awslabs/kubeflow-manifests pull request #751
Opened 2023-06-02 02:07 UTC by amitkalawat

Fix for error - Error: Unsupported argument enable_classiclink_dns_support   = null # https://github.com/hashicorp/terraform/issues/31730

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**

**Testing:**
- [ ] Unit tests pass
- [ ] e2e tests pass
- Details about new tests (If this PR adds a new feature)
- Details about any manual tests performed

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-02 18:41 UTC, surajkota requested changes

2023-06-02 18:41 UTC, surajkota commented on deployments/vanilla/terraform/main.tf
> +  version = "5.0.0"
Thanks for the PR, Could you update other stacks as well?
https://github.com/search?q=repo%3Aawslabs%2Fkubeflow-manifests%20terraform-aws-modules&type=code

2023-06-07 16:16 UTC, ananth102 commented
Looks good, will test on my end and merge.

2023-06-07 17:40 UTC, ananth102 approved these changes

2023-06-07 18:06 UTC, merged