Increasing disk size for gpu nodes
awslabs/kubeflow-manifests pull request #782
Opened 2023-08-23 16:49 UTC by ananth102

**Which issue is resolved by this Pull Request:**

DLC gpu images take up too much disk space, which leads to disk pressure errors. 

**Description of your changes:**
This PR increases the disk size from 50gb (default) to 75gb for gpu nodes.

**Testing:**
- [ ] Unit tests pass
- [ ] e2e tests pass
- Details about new tests (If this PR adds a new feature)
- Details about any manual tests performed
- Manually tested with public.ecr.aws/kubeflow-on-aws/notebook-servers/jupyter-pytorch:2.0.0-gpu-py310-cu118-ubuntu20.04-ec2-v1.0, no disk pressure errors.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-08-23 17:41 UTC, ryansteakley commented
Have we verified that this change, resolved the issue you encountered with disk-space?

2023-08-23 17:53 UTC, ananth102 commented
> Have we verified that this change, resolved the issue you encountered with disk-space?

Yea

2023-08-23 21:41 UTC, surajkota approved these changes

2023-08-23 21:46 UTC, surajkota requested changes

2023-08-23 21:46 UTC, surajkota commented on deployments/rds-s3/terraform/main.tf
> +    disk_size       = 75
can we make this a configurable var instead?

2023-08-23 22:05 UTC, ryansteakley approved these changes

2023-08-24 20:27 UTC, surajkota approved these changes

2023-08-25 04:26 UTC, merged